name: Sample C++ build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#env:
#  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        # Build the sample C++ file
        run: g++ test.cpp -o test